CREATE TABLE GENERAL_INFO
(
	PNAME 		VARCHAR2(500),
	ADDRESS		VARCHAR2(2000),
	MOBILE1		VARCHAR2(13),
	MOBILE2		VARCHAR2(13),
	BLOODGROUP	VARCHAR2(5),
	CREATE_DATE	DATE,
	Status		Number,
	Constraint "GEN_PK" Primary Key (PNAME,MOBILE1) 
);
